package org.utnrepasa.net.principal;

import javax.swing.JOptionPane;
import org.utnrepasa.net.util.Question;

/**
 *
 * @author Parisi Germán
 * @version 1.0
 */
public class VentanaPregunta extends javax.swing.JFrame {

    private static VentanaPregunta yo;
    private int idPartida;
    private int numeroPregunta;
    private Question pregunta;

    private VentanaPregunta() {
        initComponents();
    }

    public static VentanaPregunta getInstancia() {
        if (yo == null) {
            yo = new VentanaPregunta();
        }
        return yo;
    }

    public void setPregunta(Question pregunta) {
        this.pregunta = pregunta;
        lblDescripcion.setText(pregunta.getDescription());
        opt1.setText(pregunta.getOptions().get(0));
        opt2.setText(pregunta.getOptions().get(1));
        opt3.setText(pregunta.getOptions().get(2));
        opt4.setText(pregunta.getOptions().get(3));
        opt1.setSelected(false);
        opt2.setSelected(false);
        opt3.setSelected(false);
        opt4.setSelected(false);
    }

    public void setIdPartida(int idPartida) {
        this.idPartida = idPartida;
        this.lblIdPartida.setText(idPartida + "");
    }

    public void setNumeroPreguntasContestando(int n) {
        this.numeroPregunta = n;
        this.lblNumeroPreguntasContestando.setText(n + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        opt1 = new javax.swing.JRadioButton();
        opt2 = new javax.swing.JRadioButton();
        opt3 = new javax.swing.JRadioButton();
        opt4 = new javax.swing.JRadioButton();
        btnEnviar = new javax.swing.JButton();
        lblIdPartida = new javax.swing.JLabel();
        lblNumeroPreguntasContestando = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pregunta");

        buttonGroup1.add(opt1);
        opt1.setText("jRadioButton1");

        buttonGroup1.add(opt2);
        opt2.setText("jRadioButton2");

        buttonGroup1.add(opt3);
        opt3.setText("jRadioButton3");

        buttonGroup1.add(opt4);
        opt4.setText("jRadioButton4");

        btnEnviar.setText("Continuar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        lblIdPartida.setText("jLabel2");

        lblNumeroPreguntasContestando.setText("jLabel2");

        jLabel2.setText("Id de partida:");

        jLabel3.setText("Nro de pregunta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opt4)
                                    .addComponent(opt3)
                                    .addComponent(opt2)
                                    .addComponent(opt1)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(btnEnviar)))
                        .addGap(0, 160, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lblIdPartida))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lblNumeroPreguntasContestando)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdPartida)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opt3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opt4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroPreguntasContestando)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        ControladorCliente controlador = ControladorCliente.getInstancia();
        int r = -1;
        if (opt1.isSelected()) {
            r = 0;
        } else if (opt2.isSelected()) {
            r = 1;
        } else if (opt3.isSelected()) {
            r = 2;
        } else if (opt4.isSelected()) {
            r = 3;
        }
        if (pregunta.getCorrectOption() == r) {
            JOptionPane.showMessageDialog(this, "Correcto");
        } else {
            JOptionPane.showMessageDialog(this, "Incorrecto");
        }
        controlador.registrarRespuesta(idPartida, numeroPregunta, r);
        controlador.siguientePregunta(idPartida);
    }//GEN-LAST:event_btnEnviarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblIdPartida;
    private javax.swing.JLabel lblNumeroPreguntasContestando;
    private javax.swing.JRadioButton opt1;
    private javax.swing.JRadioButton opt2;
    private javax.swing.JRadioButton opt3;
    private javax.swing.JRadioButton opt4;
    // End of variables declaration//GEN-END:variables
}
